### ISSUE TITLE
[Bug] URLs in description are not properly formatted

### ISSUE THREAD

**Issue by darklinkpower** [Mithnar/PlayniteVndb#1]
As seen here:
![imagen](https://user-images.githubusercontent.com/1389286/69496977-8909da00-0e9d-11ea-9efc-564482e4ac44.png)

Links are being saved with this format:
`[url=https://vndb.org/c6498]Okabe Rintarou[/url]`

When they should be saved as:
`<a href="https://vndb.org/c6498">Okabe Rintarou</a>`

**Comment by Mithnar** [comment]
Fixed in: https://github.com/Mithnar/PlayniteVndb/commit/a5fcac37fbdb430a859bc2b516358154722cf37f

**Comment by darklinkpower** [comment]
That was fast!

**Comment by KuroThing** [comment]
> Fixed in: [a5fcac3](https://github.com/Mithnar/PlayniteVndb/commit/a5fcac37fbdb430a859bc2b516358154722cf37f)

For reference, vndb accepts urls like `v11` or other similar `{char}{id}` patterns. These would ideally be expanded to prefix the vndb.org domain.
