### ISSUE TITLE
Use VndbSharp Nuget Package

### ISSUE THREAD

**Issue by Nikey646** [Mithnar/PlayniteVndb#10]
We finally added a Nuget Package for VndbSharp.

It (currently) doesn't have user authentication added, but since this PlayNite extension doesn't manage anything to do with Vndb User Accounts, that is a non-issue.

It was added thanks to @micah686 in https://github.com/Nikey646/VndbSharp/pull/64

The Nuget package is [here](https://www.nuget.org/packages/VndbSharp)

**Comment by Mithnar** [comment]
Thanks for informing me, just added it as a Nuget Package.
