### ISSUE TITLE
Extension can't be installed in Playnite 8

### ISSUE THREAD

**Issue by darklinkpower** [Mithnar/PlayniteVndb#11]
Playnite 8 requires an `Id` property in extension manifests or will refuse to install

https://playnite.link/docs/playnite8/changelog.html
https://playnite.link/docs/playnite8/tutorials/extensionsManifest.html

![imagen](https://user-images.githubusercontent.com/1389286/96120923-e7281d00-0eb4-11eb-9a25-11796d1bff47.png)

**Comment by Mithnar** [comment]
Thanks for mentioning it, I added the property in the new Release
