### ISSUE TITLE
Search with link or code

### ISSUE THREAD

**Issue by edgar1016** [Mithnar/PlayniteVndb#13]
Would it be possible to make it so we can search for the VN using the direct URL or the VN code e.g. "v18131","18131"?

**Comment by Mithnar** [comment]
That's something that's planned for the next release

**Comment by Mithnar** [comment]
At the moment I'm thinking about looking for the id by typing in id:v18131, would that be enough for your usage?

By adding the id: field in front of it, it could be extended to adding more search options in the future. This would be more future proof then just checking for an ID-like string.

**Comment by edgar1016** [comment]
Yeah the ID would be good enough I really appreciate it.
