### ISSUE TITLE
[Bug] Enabling "Allow Sexual" Tags" option downloads an "UNKNOWN TAG" tag

### ISSUE THREAD

**Issue by darklinkpower** [Mithnar/PlayniteVndb#2]
As seen here:
![imagen](https://user-images.githubusercontent.com/1389286/69497270-9e343800-0ea0-11ea-809d-5b0b39a46e1a.png)

![imagen](https://user-images.githubusercontent.com/1389286/69497254-7d6be280-0ea0-11ea-9d47-b16bc88a47ce.png)

**Comment by Mithnar** [comment]
Found the issue, will be fixed.
Thanks for opening the other tickets aswell :)

**Comment by darklinkpower** [comment]
Nice, I'll be opening more if I find anything else (let's hope that that is not the case). And thanks to you, it's the least I can do to help the project.

**Comment by Mithnar** [comment]
Fixed in: https://github.com/Mithnar/PlayniteVndb/commit/12a358c4ad104fa8e5321bbb8809f99164d052fe
