### ISSUE TITLE
Extensions fails to load in the latest version of Playnite.

### ISSUE THREAD

**Issue by DarkNex7007** [Mithnar/PlayniteVndb#20]
Extensions fails to load in the latest version of Playnite.

Playnite Version: 9.6
Extension Version: 1.2

![image](https://user-images.githubusercontent.com/82584562/141053795-bdbf41e4-18f2-44bf-91d7-2035e351f201.png)
![image](https://user-images.githubusercontent.com/82584562/141053569-9e05c313-3334-4a28-82ba-88c17ffdb6b4.png)

Please help me if I have done anything wrong with the settings.

**Comment by 97997** [comment]
I'm having the same issue, I'm using playnite version 9.6

**Comment by ccrowles** [comment]
Same issue, apparently it's not compatible with Playnite 9.

Extension version: 1.2
Playnite version: 9.6

**Comment by 97997** [comment]
As a temporary solution, I used the version published in [this merge ](https://github.com/Mithnar/PlayniteVndb/pull/19), the one marked as [VNDBMetadata_1_2.zip](https://github.com/Mithnar/PlayniteVndb/files/7383768/VNDBMetadata_1_2.zip) and is working

**Comment by darklinkpower** [comment]
> As a temporary solution, I used the version published in [this merge ](https://github.com/Mithnar/PlayniteVndb/pull/19), the one marked as [VNDBMetadata_1_2.zip](https://github.com/Mithnar/PlayniteVndb/files/7383768/VNDBMetadata_1_2.zip) and is working

Don't use that version, it has a bug that causes VNDB tags file to be downloaded when it shouldn't.

Here is a build with the fix.
[VNDBMetadata_1_2 - 1.zip](https://github.com/Mithnar/PlayniteVndb/files/7598565/VNDBMetadata_1_2.-.1.zip)

**Comment by ccrowles** [comment]
> Don't use that version, it has a bug that causes VNDB tags file to be downloaded when it shouldn't.
> 
> Here is a build with the fix. [VNDBMetadata_1_2 - 1.zip](https://github.com/Mithnar/PlayniteVndb/files/7598565/VNDBMetadata_1_2.-.1.zip)

Thanks!

**Comment by Mithnar** [comment]
New Release is now available on the release page (same release that's provided by darklinkpower, just a different version Number)
