### ISSUE TITLE
How to hide automatic import of scores？

### ISSUE THREAD

**Issue by Hsoraa** [Mithnar/PlayniteVndb#22]
thankyou，if have this cause I don't hope to look the scores

**Comment by Mithnar** [comment]
There is currently no way to exclude a field from metadata download.

If you already have something in it, Playnight will ask you, if you want to update the score. (Just uncheck the checkbox after you did the import)

I can implement disabling Metadata download for specific fields though, sound like a useful feature.

**Comment by Mithnar** [comment]
Implemented in 2.1
