### ISSUE TITLE
Not getting any explicit or sugestive images

### ISSUE THREAD

**Issue by Kevinhag** [Mithnar/PlayniteVndb#37]
For some reason, the search is not getting any explicit or sugestive content for screenshots or covers.
Don't know if it is a new bug or somenthing changed. It was working as usual last week. 

![2022-10-10 135130](https://user-images.githubusercontent.com/20612721/194916546-28b1945d-5744-4304-b433-142fdd676ed4.png)

![2022-10-10 134746](https://user-images.githubusercontent.com/20612721/194916601-42b64a35-5235-41cf-8846-21841080d336.png)

![2022-10-10 134830](https://user-images.githubusercontent.com/20612721/194916620-be6bd7d8-73ed-4617-a4eb-7bbbce6f1c0d.png)

![2022-10-10 134932](https://user-images.githubusercontent.com/20612721/194916827-dab7b106-3bbf-430e-83be-be923fdcc4da.png)

And thanks for this amazing add-on!

**Comment by Mithnar** [comment]
I didn't change anything, but there have been changes on vndb a week ago, I'll look into it

**Comment by Mithnar** [comment]
This looks like a bug vndb introduced in their latest API update, they return a number between 0-200 instead of a number between 0.00 and 2.00.
Might also be an undocumented change, but I doubt it.

I'll wait for an answer from vndb, or just fix it in a few days for now.

**Comment by Mithnar** [comment]
Vndb Fixed the issue, should be working again for everyone.

https://vndb.org/t19198.2#last
