### ISSUE TITLE
[Bug] Tags not being downloaded when the minimum score is set at 3.0

### ISSUE THREAD

**Issue by darklinkpower** [Mithnar/PlayniteVndb#4]
Tags are not being downloaded when the minimum score is set at 3.0 and there are tags present with that score for the game you are trying to download the metadata. It just adds an "UKNOWN TAG" tag.

Setting the score to 2.9 properly downloads tags with a 2.9 and 3.0 score.

https://vndb.org/v24

![imagen](https://user-images.githubusercontent.com/1389286/69498008-ccb61100-0ea8-11ea-86fb-6e6aed1166ea.png)

![imagen](https://user-images.githubusercontent.com/1389286/69498022-ef482a00-0ea8-11ea-8532-4026700e7e0d.png)

**Comment by Mithnar** [comment]
fixed in: https://github.com/Mithnar/PlayniteVndb/commit/caaeec7db74038fc5d15e5eabce82fd95e37f156
