### ISSUE TITLE
Unable to get meta data

### ISSUE THREAD

**Issue by Ptilopsis01** [Mithnar/PlayniteVndb#42]
![image](https://github.com/Mithnar/PlayniteVndb/assets/93318731/d789fcb8-a823-4c86-b65a-5b54d15e5214)
![image](https://github.com/Mithnar/PlayniteVndb/assets/93318731/335c6669-7a21-4c71-b1ba-501c8cf1307e)
As the title said, there's no result in this plugin

**Comment by darogard78** [comment]
Same situation here, search not working.

**Comment by Ptilopsis01** [comment]
Already fixed....I doubt it might be the problem of vndb
