### ISSUE TITLE
Unable to download data

### ISSUE THREAD

**Issue by lhj5426** [Mithnar/PlayniteVndb#6]
https://i..com/hbMVNDG.png

Failed to download metadata：未能加载文件或程序集“System.ValueTuple，Version=4.0.3.0，Culture=neutral，PublicKey Token=cc7b13ffcd2ddd51”或它的某一个依赖项。系统找不到指定的文件。

System.ValueTuple，Version=4.0.3.0，Culture=neutral，PublicKey Token=cc7b13ffcd2ddd51
The system cannot find this file
  
This file does exist in the system

C:\Windows\Microsoft.NET\Framework64\v4.0.30319\System.ValueTuple.dll

Why do downloads report errors?

System version win10 x64 professional

Microsoft.NET 4.7

Playnite 7.4

**Comment by Mithnar** [comment]
Sorry for answering this late, didn't really pay attention to this :(

I made a small modification, trying to remove the dependency you're having problems with.

Could you try this out?
[PlayniteVndb-1.1.zip](https://github.com/Mithnar/PlayniteVndb/files/4466439/PlayniteVndb-1.1.zip)

**Comment by lhj5426** [comment]
Tried it so thank you developers
 Sorry for so many genius feedback
