### ISSUE TITLE
Option to Keep Original Title instead of Translated Title

### ISSUE THREAD

**Issue by Snap47** [Mithnar/PlayniteVndb#9]
Hi, me again.

I was wondering if it was possible to have an option where the user can choose to keep the Original Title (VNDB) and/or Native Title (User Already Defined), or simply disable NAME importing during the download process.

As of right now, even though in Playnite's Metadata Setting, nothing is indicating to be importing NAME, during VNDB metadata DL, it still chooses to overwrite my Native Title every time, and I'd have to click off the NAME check mark every time to prevent it.

This feature would be helpful for:
1. Untranslated VNs - in which case the VNDB translated titles means little
2. VNs translated in Non-english.

Thanks again~

**Comment by Mithnar** [comment]
The current Playnite version asks you, which metadata to import in case of overwriting data. Does this solve the issues or do you feel further adjustements are needed?

**Comment by Mithnar** [comment]
https://github.com/Mithnar/PlayniteVndb/issues/27
